name = "Firebase"
uuid = "d5d4129f-b518-43ad-8b57-4a757381be86"
authors = ["Ashwani Rathee <ab669522@gmail.com>"]
version = "0.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
GoogleCloud = "55e21f81-8b0a-565e-b5ad-6816892a5ee7"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "0.27"
GoogleCloud = "0.8"
HTTP = "0.8.19"
JSON = "0.21"
julia = "1.5"
