name = "Firebase"
uuid = "d5d4129f-b518-43ad-8b57-4a757381be86"
authors = ["Ashwani Rathee <ab669522@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GoogleCloud = "55e21f81-8b0a-565e-b5ad-6816892a5ee7"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
